### ISSUE TITLE
appTray 在manjaro系统下无法显示

### ISSUE THREAD

**Issue by liangjiezhu** [Ericwyn/electron-lark#7] opened 2020-11-25 12:04 UTC
本机信息如下：

 ██████████████████  ████████     OS: Manjaro 20.2 Nibia
 ██████████████████  ████████     Kernel: x86_64 Linux 5.4.77-1-MANJARO
 ██████████████████  ████████     Uptime: 4d 6h 47m
 ████████            ████████     Packages: 1742
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 3840x1080
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: PRO-dark-XFCE-edition II
 ████████  ████████  ████████     GTK Theme: PRO-dark-XFCE-edition II [GTK2]
 ████████  ████████  ████████     Icon Theme: Vibrancy-NonMono-Dark-Teal
 ████████  ████████  ████████     Font: Noto Sans CJK HK Light 10
 ████████  ████████  ████████     Disk: 185G / 386G (51%)
                                  CPU: Intel Core i7-10510U @ 8x 4.9GHz [59.0°C]
                                  GPU: Mesa Intel(R) UHD Graphics (CML GT2)
                                  RAM: 21380MiB / 23894MiB

无法显示 appTray

**Comment by Ericwyn** [comment] 2020-11-25 15:46
可以尝试参考一下 #6  里面提到的链接和方法

**Comment by Ericwyn** [comment] 2020-11-25 15:48
Duplicate of #6

**Comment by liangjiezhu** [comment] 2020-11-26 07:30
Thanks. Followed the comment, I solved this issue.

Here is the steps:

1. Installed xfce4-statusnotifier-plugin from AUR: yay -S xfce4-statusnotifier-plugin
2.Restart xfce
3.Enabled xfce4-statusnotifier-plugin: Right click Panel --> Add new panel, select status notifier

**Closed** 2020-11-30 02:30 UTC
